### ISSUE TITLE
WalletConnect fails

### ISSUE THREAD

**Issue by stas** [vinliao/phrasetown-connect#1]
I'm trying to connect with WC and I get a 500 error.

Looking at the request, it seems like the WC is sending a serialized JSON payload as a string. Please confirm that is the issue for others :pray: 

![Captura de ecrã de 2022-12-14 11 17 50](https://user-images.githubusercontent.com/112147/207581853-ff5b1a5b-ac10-413a-97c2-df1d3fbc36ef.png)

**Comment by vinliao** [comment]
Doesn't seem to be any mistake there. Are you signing with the seed that Farcaster gave you?

**Comment by stas** [comment]
> Doesn't seem to be any mistake there. Are you signing with the seed that Farcaster gave you?

Ah, sorry I think I got confused by the _seed that Farcaster gave_. Thanks for adding an error screen btw :heart:
